library(faraway)
data(orings)
head(orings)
lmod<-lm(damage/6 ~ temp, data=orings)
summary(lmod)
logitmod <- glm(cbind(damage,6-damage)~temp,family=binomial,data=orings)
summary(logitmod)
probitmod <- glm(cbind(damage,6-damage)~temp,family=binomial(link=probit), data=orings)
summary(probitmod)
predict(lmod,newdata = data.frame(temp = c(50,78)))
predict(logitmod,newdata = data.frame(temp = c(50,78)),type = "link")
predict(logitmod,newdata = data.frame(temp = c(50,78)),type = "response")
predict(probitmod,newdata = data.frame(temp = c(50,78)),type = "link")
predict(probitmod,newdata = data.frame(temp = c(50,78)),type = "response")

