library(faraway)
data(orings)
head(orings)
logitmod <- glm(cbind(damage,6-damage)~temp, family=binomial,data= orings)
summary(logitmod)
probitmod <- glm(cbind(damage,6-damage)~temp,family=binomial(link=probit), data=orings)
summary(probitmod)
plot(logitmod,which = 1,main="Logit link")
plot(logitmod,which = 2,main="Logit link")
plot(probitmod,which = 1,main="Probit link")
plot(probitmod,which = 2,main="Probit link")
set.seed(728)
n<-1000
X<-rnorm(n,1,1)
b0<-2
b1<--0.1
mu<-exp(b0+b1*X)
Y<-rpois(n,mu)
plot(X,Y)
f0 <- glm(Y~1,family=poisson)
f1 <- glm(Y~X,family=poisson)
rp0 <- residuals(f0,"pearson")
rd0 <- residuals(f0,"deviance")
rp1 <- residuals(f1,"pearson")
rd1 <- residuals(f1,"deviance")
mean(rp0);mean(rd0);mean(rp1);mean(rd1)
